### ISSUE TITLE
Serde and bloomfilter

### ISSUE THREAD

**Issue by gh0st42** [jedisct1/rust-bloom-filter#18]
It would be really nice if one could easily serialize and deserialize a bloom filter struct. 
I guess this would also be expected standard behavior for a rust lib according to https://rust-lang.github.io/api-guidelines/interoperability.html#data-structures-implement-serdes-serialize-deserialize-c-serde

At the moment one has to manually save the bitmap, number of bits, sip keys, etc. which is more work and might be more error-prone.

**Comment by jedisct1** [comment]
Can you implement this?

**Comment by gh0st42** [comment]
made a PR but it also required a PR to SipHash (https://github.com/jedisct1/rust-siphash/pull/12) 
All changes are simple derives and new tests, nothing fancy.
