### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by Ebedthan** [jedisct1/rust-bloom-filter#32]
Hi @jedisct1,

I believe the crate will benefit from a more detailed README. I can propose a PR if you agree.

**Comment by jedisct1** [comment]
Oh course!

A pull request would be more than welcome :)

**Comment by Ebedthan** [comment]
By the way, I have thought of a logo for the crate if you think it is a good idea. Here is a proposal. If you agree with one we can add it to the README.
![10](https://user-images.githubusercontent.com/17315349/153240054-e3a7eaae-1cbf-4dd5-8c5f-a312e9859bec.png)
![8](https://user-images.githubusercontent.com/17315349/153240067-51ee24ac-3d3f-4e9a-bb39-387cbf9ad862.png)
![7](https://user-images.githubusercontent.com/17315349/153240084-a5c034f2-1ac2-44c9-85da-92d76e7c7f8d.png)

**Comment by jedisct1** [comment]
They all look great! I like the last one :)

**Comment by Ebedthan** [comment]
Great! I'm adding it!
