### ISSUE TITLE
Provide `bloom.is_empty()` and `bloom.fill()`

### ISSUE THREAD

**Issue by k12ish** [jedisct1/rust-bloom-filter#38]
Thank you for maintaining this library!

I'm solving a puzzle with code that looks like this:

```rust
let mut vec = vec![true; 10_000];
let mut items = vec![Item::new(); 10_000];
while vec.iter().any() {
    vec = items
        .enumerate()
        .filter(|&(index, _)| vec[index])
        .map(Item::recompute)
        .collect()
}
```

I'd like to use a bloom filter instead of `bloom`, could I implement two functions that help mimic this behaviour:

#### `fn is_empty(&self) -> bool`
- Returns true if every element in the underlying bit vector is false

#### `fn fill(&mut self)`
- Sets every element in the underlying bit vector to true

**Comment by jedisct1** [comment]
Sure, why not!
