### ISSUE TITLE
Consider yanking 1.0.15

### ISSUE THREAD

**Issue by nox** [jedisct1/rust-bloom-filter#46]
Version 1.0.15 includes a bump from bit-vec 0.7 to bit-vec 0.8, which is a breaking change, and should be published as a breaking change (bloomfilter 2) to respect semver, as it is [exposed](https://docs.rs/bloomfilter/latest/bloomfilter/struct.Bloom.html#method.bit_vec) in bloomfilter's public API.

**Comment by jedisct1** [comment]
Sigh, these are internal details, that shouldn't even be exposed.

**Comment by jedisct1** [comment]
Version 2 is out, and that structure is not exposed any more.
