### ISSUE TITLE
Supporting defragmentation on the Bloom structure

### ISSUE THREAD

**Issue by KarthikSubbarao** [jedisct1/rust-bloom-filter#47]
We have a use case requiring support of defragmentation on the `Bloom` structure.

The only dynamic / heap allocated block within the `Bloom` structure is `bit_vec: BitVec`. 

During a defragmentation cycle, we can check if an allocated block needs to be defragmented by providing a pointer to it. 
In case of Bloom, we will have to provide a pointer to the overall `Bloom` structure and the underneath `bit_vec`. 

If defragmentation is needed, we will have to re-allocate these two blocks of memory.

```
pub struct Bloom<T: ?Sized> {
    bit_vec: BitVec,
    bitmap_bits: u64,
    k_num: u32,
    sips: [SipHasher13; 2],
    _phantom: PhantomData<T>,
}
``` 

To help with this, could we expose the `bit_vec` through an function or any alternative approach?

**Comment by jedisct1** [comment]
`bit_vec` is an internal implementation detail.

But public functions to support defragmentation can be added.

Would you be able to contribute this?

**Comment by KarthikSubbarao** [comment]
Thank you, @jedisct1. I have implemented a public API to allow defragmentation of the Bloom structure's `bit_vec` in the PR.

https://github.com/valkey-io/valkey-bloom/pull/25/

When possible, please take a look

**Comment by jedisct1** [comment]
Hi!

I must confess that I'm a bit confused about what this is defragmenting and what the callback function would do.

The bit vector is just a `Vec` with a fixed size.

**Comment by KarthikSubbarao** [comment]
This is for a use case where we have several (e.g. tens of thousands) of bloom filters allocated and freed using a custom allocator - not the Rust System Allocator. This can cause the fragmentation ratio on the host to increase. 

The idea is that we can use the new `defrag` API by providing a callback function that will be implemented by users of this crate. It will look similar to this snippet example:
```
            bloom.defrag(bloom_defrag_callback);
```

```
fn bloom_defrag_callback(mut vec: Vec<u32>) -> Vec<u32> {
    // Determine if defragmentation is needed on the vector.
    // If required, defragment the vector: Reallocate the vector and copy the contents to it. 
    // If not required, return the original vector.
}
```

> // Determine if defragmentation is needed on the vector. 

To provide some more information on this, in our use case, we will use the pointer to the vector and will analyze the memory regions and determine whether defragmentation should be performed based on utilization and fragmentation level.

**Comment by jedisct1** [comment]
That looks like a very specific use case, that's difficult to justify and even document for people not familiar with your peculiar application.

Maybe we could add something like a `trigger_heap_allocations` function that does a `realloc(0)` instead? A justification for that would be to randomize the address space, even though that's already a little bit far fetched.

**Comment by KarthikSubbarao** [comment]
> Maybe we could add something like a trigger_heap_allocations function that does a realloc(0) instead? A justification for that would be to randomize the address space, even though that's already a little bit far fetched.

Yes, reallocation is another use case for this.

Here are some options I can think of:

#### Option 1: Exposing `bit_vec` from [`BitStruct`](https://github.com/jedisct1/rust-bloom-filter/blob/master/src/lib.rs#L39) struct only.

With this option, a user can use the existing [`to_struct`](https://github.com/jedisct1/rust-bloom-filter/blob/master/src/lib.rs#L220) on a `Bloom` instance to obtain the `BitStruct`. Once they have this, with a new API such as `bit_vec`, the user obtain the BitVec and defragment / re-allocate the vector - and can re-create a bloom object from this when needed.

Usage of the new API:
```
let mut bloom = Bloom::new(10, 80);
let bit_struct = bloom.to_struct();
let bit_vec = bit_struct.bit_vec(); // New API
```

#### Option 2: Provide an API for the bloom structure to allow reallocating the `bit_vec` using a custom callback.

This can be named `trigger_heap_allocations` or anything similar as well. 

The reason for accepting a callback is that the reallocation (or defragmentation) can be done different by the user (not necessarily through the `realloc`).

In rust-bloom-filter:
```
    pub type BitVecReallocCb = fn(bit_vec: &mut Vec<u32>);

    pub fn realloc_bitvec(&mut self, callback: BitVecReallocCb) {
        let vec_mut = unsafe {
            self.bit_vec.storage_mut()
        };
        callback(vec_mut);
    }
```

Usage of the new API:
```
let mut bloom = Bloom::new(10, 80);
bloom.realloc_bitvec(realloc_callback);  // New API
```

**Comment by jedisct1** [comment]
Version 3.0.0 has a `realloc_large_heap_allocated_objects()` function, but I still don't get what it's for.
