### ISSUE TITLE
Support omitting the seed from serialised representation (from `into_bytes/to_bytes`)

### ISSUE THREAD

**Issue by joseph-isaacs** [jedisct1/rust-bloom-filter#50]
I am using this bloom filter is a memory constrained file, where each bloom filter is sized to max 128 bytes. We can fix the seed ahead of time. 

It would be great if the seed could be omitted from the serialised representation (from `into_bytes/to_bytes`). 

Maybe something like `to_bytes_without_seed(&self)` and `from_bytes_with_seed(bytes, seed)`. Do you think this could be supported?

**Comment by jedisct1** [comment]
Objectively, probably not. That would complicate the code quite a bit (the header currently has a fixed size), for a use case that's quite specific. As I don't use that crate any more, I'd like to avoid adding too many rarely used features, that would still have to be maintained forever.
