### ISSUE TITLE
Feature request: ability to accept "raw" pre-hashed values

### ISSUE THREAD

**Issue by ketralnis** [jedisct1/rust-bloom-filter#7]
In trying to construct a large bloomfilter I'm finding that the actual hashing is a significant bottleneck that can't easily be parallelised when access to the bloomfilter must be serialised.

It would be nice if there were a way to hash the structure myself before passing into the bloomfilter. In that case, hashing and modifying the bloom filter could be done in different threads. Today this isn't possible because even if I did hash them myself then bloomfilter would [just to it again itself](https://github.com/jedisct1/rust-bloom-filter/blob/master/src/bloomfilter/lib.rs#L101).

If you'd accept a patch that implements this I may be able to have a go of it myself and send a PR

**Comment by jedisct1** [comment]
That's not a very common use case, but if the patch is not too invasive, I'd be glad to merge it!

**Comment by ketralnis** [comment]
Moving to https://github.com/jedisct1/rust-bloom-filter/pull/8
